### PR TITLE
swarm: Migrate p2p/simulations from go-ethereum

### PR DESCRIPTION
**Pull request by chadsr**
This PR coupled with [this go-ethereum PR](https://github.com/ethereum/go-ethereum/pull/20122) migrates `p2p/simulations` from the `go-ethereum` repository to here. _(Technically it also migrates `p2p/testing`, but it is already duplicated in this repo)_

Motivation for this came about from #1799, where that PR depended on a `go-ethereum` PR. @acud pointed out that it would in-fact make more sense to migrate `p2p/simulations` package to `ethersphere/swarm`.

I refrained from renaming the package, to avoid any confusion. I do feel like it could be refactored to somewhere else though (there are 3-4 simulation related packages scattered around), but I will leave that for core devs to decide. :)

### CODE REVIEW

**Comment by acud** [comment]
@Chadsr build is [broken](https://travis-ci.org/ethersphere/swarm/builds/589002324?utm_source=github_status&utm_medium=notification)

**Comment by chadsr** [comment]
> @Chadsr build is [broken](https://travis-ci.org/ethersphere/swarm/builds/589002324?utm_source=github_status&utm_medium=notification)

@acud Yeah, apologies, my IDE bugged out yesterday and apparently let me down. 

However I'm not sure if this PR is a good idea anymore? After [finding some complications and what @fjl just added](https://github.com/ethereum/go-ethereum/pull/20122), i'm thinking it might be more appropriate that the packages stay in go-ethereum?

**Comment by chadsr** [comment]
Going to close this, as it seems best to keep p2p/simulations in go-ethereum after all.

**Comment by zelig** [comment]
hmm, i thought it was a good idea, given noone is using this and we maintain it...

**Comment by chadsr** [comment]
Reopening to facilitate some more discussion.
@zelig The package is used by one or two tests in go-ethereum. It seems fjl is keen on keeping the option to use it further in go-ethereum as well.

As an outsider, I see these options (but maybe there are more):
- Continue the migration and use the swarm package as a dependency in go-ethereum.
- Duplicate the package, so that swarm and go-ethereum maintain their own versions. Swarm version could then just be unified with the swarm specific simulation packages that already exist.
- Keep it in go-ethereum and remain reliant on their release cycle.

**Comment by acud** [comment]
if go-ethereum are using this library then let's not migrate this. let's just PR stuff into go-ethereum and vendor it again. let's just make sure we are not dependent on them to approve this stuff - if we are the codeowners then let's maintain this code (or at least tell geth to vendor this from us so we can actively maintain it)

**Comment by acud** [comment]
@nonsense @skylenet can I have your input on this? I'd rather we don't maintain duplicate code here and on go-ethereum, and I guess you two would be able to hook it up easily right?

**Comment by acud** [comment]
@Chadsr do we still need this PR? I think due to the fact you've submitted the `go-ethereum` PR this is no longer needed right?

**Comment by chadsr** [comment]
@acud Only useful if others from the core team still want to give input, I guess. It's not needed in relation to anything else from me, so feel free to close it.

**Pull request closed without merging**
