### PR TITLE
Dockerfile: add kernel profiler to alltools image

### PR DESCRIPTION
**Pull request by acud**
This PR adds the linux kernel `perf` tool to the `alltools` docker image.

### CODE REVIEW

**Comment by acud** [comment]
@nonsense we need to update `swarm.service.yaml` with the appropriate sysctl.
EDIT: or to add `sysctl -p` to the entry point

**Comment by acud** [comment]
https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/

**Comment by acud** [comment]
https://stackoverflow.com/questions/44439372/how-to-pass-sysctl-flags-to-docker-from-k8s

**Review by janos — COMMENTED** [review]
Maybe we could have a different image with perf tools, not to pollute the official one?

**Comment by acud** [comment]
@janos although this is the official one but I've intentionally added the changes to the `alltools` build (as opposed to the normal `Dockerfile`)  which includes also the smoke tests binary, jaeger etc. I think this is the correct place for it

**Comment by acud** [comment]
removing this from here as it is in the new stream PR. let's integrate it from there

**Pull request closed without merging**
