### PR TITLE
swarm/pss: Rename "self" receivers to reflect better their identity

### PR DESCRIPTION
**Pull request by skylenet**
Related issue: https://github.com/ethersphere/go-ethereum/issues/574

### CODE REVIEW

**Comment by nolash** [comment]
@skylenet hey thanks for this PR. Let me know if/when it's ready for review! :)

**Comment by skylenet** [comment]
@nolash it’s ready for a review. Feel free to add the right labels :) Seems like I can’t do that.

**Comment by acud** [comment]
@nolash aren't part of these changes addressed as part of @dleonard00 's open PR?

**Comment by nolash** [comment]
@justelad are they? I haven't looked at that PR yet myself.

**Comment by acud** [comment]
i stand corrected... my mistake ☮️

**Comment by nonsense** [comment]
LGTM, although this might result in conflicts with a few of @nolash PRs - I am not sure which one you guys want to merge first.

**Review by nolash — APPROVED** [review]
LGTM. Thanks @skylenet

**Comment by skylenet** [comment]
Thanks for reviewing and merging 👍

**Pull request merged**
