### PR TITLE
swarm/storage/localstore: global batch write lock

### PR DESCRIPTION
**Pull request by janos**
This PR removes address lock for writing leveldb batches and leaves only global batch write lock. This reduces code complexity for storing gc index size (number of items in gc index). This change is based on results from BenchmarkPutUpload https://github.com/ethersphere/go-ethereum/pull/1032/files#diff-5387d95639737e244cbf93d01682aa2dR215

```
BenchmarkPutUpload/count_100_parallel_1-addr_lock-8         	     300	   5075184 ns/op	 2081455 B/op	    2374 allocs/op
BenchmarkPutUpload/count_100_parallel_1-glob_lock-8         	     300	   5032374 ns/op	 2061207 B/op	    1772 allocs/op
BenchmarkPutUpload/count_100_parallel_2-addr_lock-8         	     300	   5079732 ns/op	 2081731 B/op	    2370 allocs/op
BenchmarkPutUpload/count_100_parallel_2-glob_lock-8         	     300	   5179478 ns/op	 2061380 B/op	    1773 allocs/op
BenchmarkPutUpload/count_100_parallel_4-addr_lock-8         	     500	   3748581 ns/op	 2081535 B/op	    2323 allocs/op
BenchmarkPutUpload/count_100_parallel_4-glob_lock-8         	     300	   5367513 ns/op	 2061337 B/op	    1774 allocs/op
BenchmarkPutUpload/count_100_parallel_8-addr_lock-8         	     500	   3311724 ns/op	 2082696 B/op	    2297 allocs/op
BenchmarkPutUpload/count_100_parallel_8-glob_lock-8         	     300	   5677622 ns/op	 2061636 B/op	    1776 allocs/op
BenchmarkPutUpload/count_100_parallel_16-addr_lock-8        	     500	   3606605 ns/op	 2085559 B/op	    2282 allocs/op
BenchmarkPutUpload/count_100_parallel_16-glob_lock-8        	     300	   6057814 ns/op	 2062032 B/op	    1780 allocs/op
BenchmarkPutUpload/count_100_parallel_32-addr_lock-8        	     500	   3720995 ns/op	 2089247 B/op	    2280 allocs/op
BenchmarkPutUpload/count_100_parallel_32-glob_lock-8        	     200	   6186910 ns/op	 2062744 B/op	    1789 allocs/op
BenchmarkPutUpload/count_1000_parallel_1-addr_lock-8        	      20	  84397760 ns/op	25210142 B/op	   23222 allocs/op
BenchmarkPutUpload/count_1000_parallel_1-glob_lock-8        	      20	  83432699 ns/op	25011813 B/op	   17222 allocs/op
BenchmarkPutUpload/count_1000_parallel_2-addr_lock-8        	      20	  80471064 ns/op	25208653 B/op	   23182 allocs/op
BenchmarkPutUpload/count_1000_parallel_2-glob_lock-8        	      20	  87841819 ns/op	25008899 B/op	   17223 allocs/op
BenchmarkPutUpload/count_1000_parallel_4-addr_lock-8        	      20	  71364750 ns/op	25206981 B/op	   22704 allocs/op
BenchmarkPutUpload/count_1000_parallel_4-glob_lock-8        	      20	  91491913 ns/op	25013307 B/op	   17225 allocs/op
BenchmarkPutUpload/count_1000_parallel_8-addr_lock-8        	      20	  67776485 ns/op	25210323 B/op	   22315 allocs/op
BenchmarkPutUpload/count_1000_parallel_8-glob_lock-8        	      20	  88658733 ns/op	25008864 B/op	   17228 allocs/op
BenchmarkPutUpload/count_1000_parallel_16-addr_lock-8       	      20	  61599020 ns/op	25213746 B/op	   22000 allocs/op
BenchmarkPutUpload/count_1000_parallel_16-glob_lock-8       	      20	  92734980 ns/op	25012744 B/op	   17228 allocs/op
BenchmarkPutUpload/count_1000_parallel_32-addr_lock-8       	      20	  57465216 ns/op	25224471 B/op	   21844 allocs/op
BenchmarkPutUpload/count_1000_parallel_32-glob_lock-8       	      20	  92420562 ns/op	25013237 B/op	   17244 allocs/op
BenchmarkPutUpload/count_10000_parallel_1-addr_lock-8       	       2	 611387455 ns/op	216747724 B/op	  248218 allocs/op
BenchmarkPutUpload/count_10000_parallel_1-glob_lock-8       	       2	 616212255 ns/op	214871528 B/op	  188983 allocs/op
BenchmarkPutUpload/count_10000_parallel_2-addr_lock-8       	       2	 576871975 ns/op	216552736 B/op	  246849 allocs/op
BenchmarkPutUpload/count_10000_parallel_2-glob_lock-8       	       2	 601008305 ns/op	214713748 B/op	  188931 allocs/op
BenchmarkPutUpload/count_10000_parallel_4-addr_lock-8       	       2	 551001371 ns/op	216701032 B/op	  241935 allocs/op
BenchmarkPutUpload/count_10000_parallel_4-glob_lock-8       	       2	 605576690 ns/op	214719292 B/op	  188949 allocs/op
BenchmarkPutUpload/count_10000_parallel_8-addr_lock-8       	       2	 504949238 ns/op	216431280 B/op	  236326 allocs/op
BenchmarkPutUpload/count_10000_parallel_8-glob_lock-8       	       2	 611631748 ns/op	214809276 B/op	  188957 allocs/op
BenchmarkPutUpload/count_10000_parallel_16-addr_lock-8      	       3	 510030296 ns/op	216088080 B/op	  231171 allocs/op
BenchmarkPutUpload/count_10000_parallel_16-glob_lock-8      	       2	 611416284 ns/op	214855916 B/op	  189724 allocs/op
BenchmarkPutUpload/count_10000_parallel_32-addr_lock-8      	       3	 481631118 ns/op	215341840 B/op	  224716 allocs/op
BenchmarkPutUpload/count_10000_parallel_32-glob_lock-8      	       2	 633612977 ns/op	214904164 B/op	  189775 allocs/op
BenchmarkPutUpload/count_100000_parallel_1-addr_lock-8      	       1	23289076334 ns/op	2354337552 B/op	 4190917 allocs/op
BenchmarkPutUpload/count_100000_parallel_1-glob_lock-8      	       1	22155535580 ns/op	2312803760 B/op	 3455566 allocs/op
BenchmarkPutUpload/count_100000_parallel_2-addr_lock-8      	       1	21908455154 ns/op	2328191128 B/op	 4014009 allocs/op
BenchmarkPutUpload/count_100000_parallel_2-glob_lock-8      	       1	22956308053 ns/op	2325078528 B/op	 3530270 allocs/op
BenchmarkPutUpload/count_100000_parallel_4-addr_lock-8      	       1	22334786914 ns/op	2338677488 B/op	 4028700 allocs/op
BenchmarkPutUpload/count_100000_parallel_4-glob_lock-8      	       1	23222406988 ns/op	2334153480 B/op	 3580197 allocs/op
BenchmarkPutUpload/count_100000_parallel_8-addr_lock-8      	       1	21569685948 ns/op	2322310120 B/op	 3880022 allocs/op
BenchmarkPutUpload/count_100000_parallel_8-glob_lock-8      	       1	22730998001 ns/op	2318311616 B/op	 3494378 allocs/op
BenchmarkPutUpload/count_100000_parallel_16-addr_lock-8     	       1	22005406658 ns/op	2324345744 B/op	 3862100 allocs/op
BenchmarkPutUpload/count_100000_parallel_16-glob_lock-8     	       1	24246335163 ns/op	2341373784 B/op	 3626749 allocs/op
BenchmarkPutUpload/count_100000_parallel_32-addr_lock-8     	       1	22764682771 ns/op	2332867552 B/op	 3896808 allocs/op
BenchmarkPutUpload/count_100000_parallel_32-glob_lock-8     	       1	24617688531 ns/op	2343609240 B/op	 3647404 allocs/op
```

As expected, global lock introduces performance penalty, but in much less degree then expected.
Higher levels of parallelization do not give high level of performance boost. For 8 parallel
uploads on 8 core benchmark, the speedup is only ~1.72x at best. There is no significant difference
when a larger number of chunks is uploaded.

Please, leave your opinions about this change.

### CODE REVIEW

**Comment by nonsense** [comment]
I am all up for simpler code, I think this is not a huge penalty to pay.

**Review by nonsense — APPROVED** [review]

**Comment by zelig** [comment]
I think 1.7 is massively significant. I would keep address lock now that we got it already

**Comment by janos** [comment]
@zelig ok, in that case, I should remove global lock option from `localstore` branch.

**Comment by janos** [comment]
Global lock is removed from `localstore` branch. Do we have a decision which lock should be used?

**Comment by nonsense** [comment]
I think we should merge this - code is simpler, and optimising for this locking now is premature.

1.7x improvement is just on one benchmark for only a few chunks - it might very well have been a fluke - we have no information if this is the case that happens on production, I would argue that on production we are more probably hitting the cases in thousands of chunks.

Let's aim for correctness, and not for optimising code we don't even now is a bottleneck.

**Comment by nonsense** [comment]
> I think 1.7 is massively significant. I would keep address lock now that we got it already

The code is massively more complicated with address lock.

1.7x is a made up number by a single benchmark out of many, without us knowing the most common case in real usage of Swarm.

Having heard @janos explain all the details about garbage collection with address lock, I'd much rather we don't merge the `address lock` version of the code, but the simpler `global lock` version.

**Review by zelig — APPROVED** [review]

**Review by zelig — CHANGES_REQUESTED** [review]
I think global locking should be avoided if possible. and it is possible, done, tested and benchmarked.

**Comment by nonsense** [comment]
@zelig what is your reasoning to base your decision on the benchmark `count_100_parallel_8` and not on `count_100000_parallel_8` or `count_10000_parallel_8`?

We are yet again doing premature optimisation in a place of the codebase that we have no idea or proof that is a bottleneck, at the cost of much more complicated code.

**Comment by frncmx** [comment]
@janos do you have the code somewhere what I could reproduce your results with?
The link in the description seems to run the benchmarks just for one type of locking.

**Comment by janos** [comment]
@frncmx yes, this is the last commit before the global lock option was removed from the localstore branch https://github.com/ethersphere/go-ethereum/blob/ebecd055eb45281d731a9a106ba75858aa1bd68c/swarm/storage/localstore/mode_put_test.go#L270

**Comment by zelig** [comment]
closed as global lock was now decided against

**Comment by frncmx** [comment]
just FYI; as I'mt late, but I only played with these benchmarks today

- I focused on high parallelism and large chunk numbers.
- I run the benchmarks separately so I can use `benchcmp`.
- The machine I used was an AWS EC2 `m5a.2xlarge` type (8 vCPU, 4 cores, 2 threads - 30 GB of RAM).
- Also I increased `-benchtime` so benchmarks run more than once to get a more statistically significant result. ([This article](https://dave.cheney.net/2013/06/30/how-to-write-benchmarks-in-go) has nice explanation on how number or runs are decided.)

**the results** 

```
$ ~/code/bin/benchcmp addr-lock.txt global-lock.txt 
benchmark                                         old ns/op       new ns/op       delta
BenchmarkPutUpload/count_100000_parallel_4-8      20954101872     21308609249     +1.69%
BenchmarkPutUpload/count_100000_parallel_32-8     19723720084     22006559308     +11.57%

benchmark                                         old allocs     new allocs     delta
BenchmarkPutUpload/count_100000_parallel_4-8      4042293        3563233        -11.85%
BenchmarkPutUpload/count_100000_parallel_32-8     3793009        3585228        -5.48%

benchmark                                         old bytes      new bytes      delta
BenchmarkPutUpload/count_100000_parallel_4-8      2340243336     2328838598     -0.49%
BenchmarkPutUpload/count_100000_parallel_32-8     2315023412     2332490913     +0.75%
```

Note: the benchmarks did not put a heavy load on the machine nor high memory usage

**Comment by janos** [comment]
@frncmx thanks, that are great benchmarks. I think that most relevant comparisons would be between non-parallel uploads (parallel_1) and uploads parallel at exact the value of total CPUs (or hyperthreads r vCPUs) (parallel_8 for m5a.2xlarge). But this results are not much in favour of address lock, as I see it.

**Comment by janos** [comment]
And I noticed locally that no matter how many parallel writes or batch writes there are on leveldb, only one cpu core is used completely with additional load on another one, so up to two cores, not more. This looks like to me as a limitation of library, for now, I did not investigate more on that.

**Comment by frncmx** [comment]
Ok, I'll run the benchmarks with parallel_1 and parallel_8.

Regardless of the benchmarks results - especially because the results are not like 10x-30x difference - I agree with the decision to go with the simpler code. So that we avoid local optimizations. :+1: 

I'll post the results soon.

**Comment by frncmx** [comment]
@janos  here are the results for  `parallel_1` and `parallel_8`:
```
$ ~/code/bin/benchcmp addr-lock.txt global-lock.txt 
benchmark                                        old ns/op       new ns/op       delta
BenchmarkPutUpload/count_100000_parallel_1-8     21380442117     21017047173     -1.70%
BenchmarkPutUpload/count_100000_parallel_8-8     20181314512     21417761578     +6.13%

benchmark                                        old allocs     new allocs     delta
BenchmarkPutUpload/count_100000_parallel_1-8     4203242        3538019        -15.83%
BenchmarkPutUpload/count_100000_parallel_8-8     3969557        3587679        -9.62%

benchmark                                        old bytes      new bytes      delta
BenchmarkPutUpload/count_100000_parallel_1-8     2355745941     2324852004     -1.31%
BenchmarkPutUpload/count_100000_parallel_8-8     2335094944     2333014752     -0.09%
```

**Comment by janos** [comment]
Thanks @frncmx. Only 6% gain for fully 8x parallelization for 100k chunks, very similar to local benchmarks.

**Comment by janos** [comment]
Reopening as a result of recent discussion on problems with gc size value update synchronizations.

**Review by zelig — APPROVED** [review]

**Review by nonsense — APPROVED** [review]
Once this is merged, if stable for a few days/weeks, we should add instrumentation and dashboards to Grafana, so that we monitor performance and decide if at some point this becomes a bottleneck.

I believe `localstore` won't be a bottleneck for a while, but we should start measuring its performance now, and build intuition on how fast it is for production work-loads (I know we don't really have a concrete definition for this, but still... :) ).

**Comment by janos** [comment]
Thanks for reviews. Yes, @nonsense you are right metrics are required before localstore is actively used.

This changes are submitted upstream https://github.com/ethereum/go-ethereum/pull/19245

**Pull request closed without merging**
