### PR TITLE
Use swarm/mock/mem as mock global store

### PR DESCRIPTION
**Pull request by janos**
This is an example as alternative to https://github.com/ethereum/go-ethereum/pull/18141.

### CODE REVIEW

**Comment by nonsense** [comment]
@janos yes, this makes much more sense compared to what I did :)

I got confused with the `GlobalStorer` interface and the `state.Store`.

I reverted my changed, but we could probably merge this as I don't see a reason for use to hit the disk with these tests. What do you think?

**Comment by janos** [comment]
@nonsense I am completely fine to merge this changes, if they are approved.

**Comment by nonsense** [comment]
lgtm

**Review by zelig — APPROVED** [review]

**Comment by janos** [comment]
Submitted https://github.com/ethereum/go-ethereum/pull/18157.

**Pull request closed without merging**
