### PR TITLE
Fix data race in TestNetworkID test

### PR DESCRIPTION
**Pull request by janos**
This PR fixes data races described in https://github.com/ethersphere/go-ethereum/issues/1112 issue.

### CODE REVIEW

**Review by nonsense — APPROVED** [review]

**Review by zelig — APPROVED** [review]

**Review by frncmx — APPROVED** [review]
lgtm :+1: 

1st I was surprised we can shutdown the network, i.e., `for all nodes: node.Stop()` . I thought nodes would drop peers and lose their Kademila table. Then I realized the whole `kademlias` is populated for the test in a node service.

Smart, simple solution.

**Comment by frncmx** [comment]
Maybe you already know :) 

tip: if the commit message includes `fixes:  ethersphere/go-ethereum#1112` it would automatically close the issue when the commit lands on master. 
[Closing issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/)

**Comment by janos** [comment]
Submitted to upstream https://github.com/ethereum/go-ethereum/pull/18460.

**Comment by janos** [comment]
Thank you all for reviews. :)

**Pull request closed without merging**
