### PR TITLE
metrics evaluation - statsd timers vs go-metrics timers

### PR DESCRIPTION
**Pull request by nonsense**
cc @gbalint @lmars 

This PR is an experiment to add a resetting timer to `go-metrics`, and evaluate it against the statsd resetting timer.

TODO:
- [x] add percentiles (50%, 95%, 99%)
- [x] add tags to registry ; review if it possible to add tags to measurements

### CODE REVIEW

**Comment by nonsense** [comment]
These timers measure latency much more accurately than the exponentially decaying reservoir.

screen shot 2018-01-15 at 15 28 55

**Comment by lmars** [comment]
LGTM, do you plan to PR the change to the go-metrics lib or maintain a fork?

**Comment by nonsense** [comment]
@lmars probably maintain a fork, considering how many times go-metrics has been forked so far.

**Comment by nonsense** [comment]
@holisticode I suggest as next step we merge this together with your PR, and try it out on the cluster.

**Comment by lmars** [comment]
OK, well it may be worth considering maintaining the fork inside go-ethereum (like was done for the [log package](https://github.com/ethereum/go-ethereum/blob/master/log/README_ETHEREUM.md)).

**Comment by nonsense** [comment]
@lmars thanks for the heads-up. Will discuss this with Peter and see how to handle the fork.

**Comment by nonsense** [comment]
This PR is not out-dated. We have created a PR on `go-ethereum` to vendor the `go-metrics` and `go-metrics-influxdb` libraries with the ResettingTimer functionality, and alongside we are working on PRs with the actual instrumentation within the code.

The evaluation between statsd and go-metrics is pretty much done, and we have decided to move forward with go-metrics and introduce new types within it.

**Pull request closed without merging**
