### PR TITLE
Tiding up TestCache | Issue 390 (partial)

### PR DESCRIPTION
**Pull request by Mistra**
I'm trying to solve issue #390.
This is just a rewrite of one test, let me know if the modifications are acceptable and target the problem.

### CODE REVIEW

**Comment by gbalint** [comment]
@Mistra Thanks for contribution! Please use gofmt to format your code (imho best is to setup your editor to format the code automatically on save), the linter job fails because of this: https://travis-ci.org/ethersphere/go-ethereum/jobs/368138107

**Review by nolash — COMMENTED** [review]
Thanks for your contribution.

To be honest, it wasn't really the `TestCache` test I was thinking of, as it is pretty short and concise as it is. I should have been explicit about this, of course, and for that I apologize.

The tests that I would like reviewed for possible edits are the  `swarm/pss/pss_test.go.TestSend*` and the benchmarks . Also, we should see if more code can be shared between `swarm/pss/protocol_test.go`, `swarm/pss/handshake_test.go` and `swarm/pss/pss_test.go`

You've also included some edits on the `fuse` test in this PR. If you believe the `fuse` tests could use an overhaul too, then please let's discuss it first, and if we proceed let's create a separate PR for that.

**Comment by Mistra** [comment]
All right, I've closed this issue since the code modified was the wrong one.
Just to understand I got what you meant correctly:
I see (for instance) into testSendSym, testSendRaw, testSendAsym copy/pasted code. I'd like to encapsulate it into multiple functions to have a more modular and self-commenting flow. Could it work like that?

**Comment by nolash** [comment]
@Mistra that sounds promising

**Pull request closed without merging**
