### PR TITLE
cmd/swarm: change version of swarm binary

### PR DESCRIPTION
**Pull request by nonsense**
This should have been merged together with the bump of protocol versions due to the OpenTracing backward-incompatible change.

### CODE REVIEW

**Comment by nonsense** [comment]
This is by no means supposed to address the issues we have with respect to releasing Swarm.

However I looked into supporting both ver 5 and ver 4 of the protocols, and think this is not a very easy and straight-forward change.

Therefore I suggest we at least merge this, so that the Swarm binary reports an adequate version, and continue with:
1. Defining an exact release process for Swarm, and what we mean when we use the word release. At the moment it is overloaded, because according to different people/docs it means:
- a Geth release, which also releases Swarm under the geth-and-tools and also pushes the swarm debian package (using the Geth versioning)
- a merge to go-ethereum/master (according to our docs)
- a "major" Swarm release, similar to the 0.3 one - accompanied by a blog post, etc.
- a deployment to our "production" cluster - swarm-gateways.net

2. As part of the release process, we decide how to handle versioning for the foreseeable future - currently Swarm versioning and Swarm's debian package versioning is completely different.

**Review by janos — APPROVED** [review]

**Review by cobordism — COMMENTED** [review]
I agree that with the version change of the bzz protocol, we now need to bump the version number.
But what happens when the next geth release triggers the new build for the ubuntu ppa and elsewhere? How, when and where do we release 0.3.1 to the public?

**Review by zelig — APPROVED** [review]

**Comment by nonsense** [comment]
@zelig we agreed that we won't be merging to `master` on `ethersphere`.

This has already been merged on `go-ethereum/master` and I should have just closed this PR after that.

**Comment by nonsense** [comment]
@homotopycolimit I don't have answers to all your questions, but this is the idea I have right now:
1. Disable `swarm` from `ci/build.go`, so that next version (which currently is `0.3.1-unstable`) doesn't replace the ubuntu ppa package.
2. Review again how we can on-demand release swarm and upgrade the swarm ubuntu package.
3. Discuss with @karalabe Geth release process, so that Swarm team is aware of each release and can include notes to the users.
4. Write a release process document for Swarm so that it is clear what we mean by release, where we publish it (reddit thread, swarm gitter channel, blog post on ethereum.org (only for major releases), etc.)

---

The way I see it, current `master` is 0.3.1-unstable (which unfortunately is not compatible with 0.3.0 but there isn't much we can do, without a lot of engineering effort). So we just need to sort out the ubuntu release, and discuss internally how we communicate this with the community.

I hope this makes sense. I will be working on this today and tomorrow, so we can have a chat if you have any suggestions/ideas/concerns!

**Pull request merged**
