### PR TITLE
Disabling flaky tests

### PR DESCRIPTION
**Pull request by skylenet**
Relates to https://github.com/ethersphere/swarm/issues/1456

### CODE REVIEW

**Comment by nonsense** [comment]
Related: https://github.com/ethersphere/swarm/issues/1453

@skylenet @acud I realise that this is a flaky test, but this is literally a test we merged a few days ago.

This is one of the reason I don't like the Simulation framework for our integration tests, it seems like there are at least a few reasons why tests could be failing on it:
1. It is buggy and racy and we get keep on getting hit by race conditions when we write a test on top of it.
2. Some of the underlying components are racy, resulting in a correct simulation with correct test actually failing due to a bug in an underlying component (Kademlia?)
3. It is too difficult to use correctly, since we keep on writing racy tests for it
4. The simulation tests do not give enough feedback on what has happened so that we debug the failure.

Because of all this, I have resorted to adding integration tests to the `smoke-test` suite - it might be slower and less automated, but at least we can figure out what is going on when a failure happens.

With the tests in the Simulation framework it seems we are running in circles, adding tests with a lot of effort, and then disabling them a week later, when they fail.

What do you think?

**Comment by acud** [comment]
@nonsense i'm kind of halfway with you there, the simulations are indeed no good for CI, but they are of use, so it is indeed a question on how and when to run them. i personally am able to make use of them locally and trace them out, but yeah on the CI when they fail - it's pretty useless and you'd have to reproduce the problem locally anyway.
that being said - it is not completely useless to have the CI fail every now and then to show us that these things are indeed flaky.. so... i can't really say i lean in one direction or another.
but yeah the simulations and apparently the whole testing framework is not so stable, there's still some artifacts popping up here and there, but i'm not sure that getting rid of it is getting us closer to the target.

**Comment by acud** [comment]
about the star network test - i thought that the lowered parameters would make it not flake... i was apparently wrong. with this specific test the original idea was to actually merge it disabled (we knew it was about to fail beforehand), so it's basically my bad. it should have been already disabled upon merge

**Comment by skylenet** [comment]
I can't argue against the simulation framework because I really haven't tried using it yet. But, from what I've heard I do actually like the approach that we can programmatically setup these kind of tests. As @nonsense mentioned it's important that we can debug such tests whenever they fail, which atm seems to be a pain in the ass.

I would like to probably spend some time with this framework as I've also mentioned that I have some interest about adding a remote k8s adapter for it. 

That said, I would like to split unit from integration tests. Currently we're running all these integration tests (simulation framework) 6 times on our CI environments. I think this doesn't make sense. 

Some suggestions:
- Split unit from integration tests so that we do run unit tests often and only run integration tests once.
- Make integration tests configurable (e.g. allow changing between adapters) by providing some flags to the test. I know this will require some work... 
- Add the metrics/tracing stack to the integration tests.

**Comment by acud** [comment]
there's general agreement with your suggestions @skylenet. Also please note that the ACT tests are also flaking (i think its TestACTWithoutBogus). We've just seen it flip on the pairing session, please disable it too

**Comment by nonsense** [comment]
I like the suggestions - metrics/tracing stack on the integration tests would definitely help.

Another point is - the code is not written in a way where we can easily split logs between different nodes - if you run locally a simulation with 8 nodes, you will have a hard time splitting the logs between nodes - something that is trivial with the smoke-test integration test suite.

This particular test also failed locally btw. Maybe we should setup an integration test suite where we run these with -count=10 or something so that we quickly determine if they are flaky or not?

**Review by nonsense — APPROVED** [review]

**Comment by skylenet** [comment]
> TestACTWithoutBogus

@acud  I ran this one locally with `go test github.com/ethersphere/swarm/cmd/swarm -run 'TestACT/ACTWithoutBogus'  -count=200` and wasn't able to see it flaking. Are you sure that was the one?

**Comment by skylenet** [comment]
> 
> This particular test also failed locally btw. Maybe we should setup an integration test suite where we run these with -count=10 or something so that we quickly determine if they are flaky or not?

Yes that's a good idea. It would work well as a job that can run periodically on master. If we would run it on PRs it would require too much time.

Maybe it would be cool to have certain commands on PRs that would allow us to extend the tests. e.g. by default you don't run the flake detector, but if you say "Test for flakes" in a PR comment, we could trigger this `-count=10` job on a separate CI job.

**Pull request merged**
