### PR TITLE
swarm: wrap logger with stats for Warn, Crit and Error

### PR DESCRIPTION
**Pull request by nonsense**
This PR will give us a baseline for number of Warnings, Errors, etc. from one deployment to the next.

### CODE REVIEW

**Comment by nonsense** [comment]
Probably a good idea to try this out, before merging (provided you agree it is useful).

**Review by janos — COMMENTED** [review]
It appears that many functions and types from log package is missing in swarm/log. Unfortunately, I do not think that it is easy to wrap it without more code.

```
swarm/fuse/swarmfs_test.go:46:2: undefined: "github.com/ethereum/go-ethereum/swarm/log".PrintOrigins
swarm/fuse/swarmfs_test.go:47:2: undefined: "github.com/ethereum/go-ethereum/swarm/log".Root
swarm/fuse/swarmfs_test.go:47:24: undefined: "github.com/ethereum/go-ethereum/swarm/log".LvlFilterHandler
swarm/fuse/swarmfs_test.go:47:45: undefined: "github.com/ethereum/go-ethereum/swarm/log".Lvl
swarm/fuse/swarmfs_test.go:47:65: undefined: "github.com/ethereum/go-ethereum/swarm/log".StreamHandler
swarm/fuse/swarmfs_test.go:47:115: undefined: "github.com/ethereum/go-ethereum/swarm/log".TerminalFormat
...
```

**Comment by nonsense** [comment]
We don't really need this in tests, so I removed the wrapping from tests.

**Review by janos — APPROVED** [review]
Great. Thanks, Anton.

**Comment by nonsense** [comment]
This is working well on the cluster, so I suggest we merge it. @gbalint ?

**Review by gbalint — APPROVED** [review]

**Pull request merged**
