### PR TITLE
pss, swarm: condition trojan chunk inspection

### LINKED ISSUE #2163: add conditions for trojan chunk callbacks
(issue stemming from unresolved thread in #2158)

iterate the store hook call implementation so that the callback is only executed for chunks that are:
- ~content-addressed~ #2201
- ~close to the node address~ (see #2167)
- ~not already present in the localstore~ #2201

(in addition to also being valid, which is already true for the current code)

see thread [here](https://github.com/ethersphere/swarm/pull/2158#discussion_r410667602)

### PR DESCRIPTION
**Pull request by mortelli**
This PR attempts to solve issue #2163, which is about **calling trojan chunk inspection only for content-addressed chunks and ones that are not already present in the localstore**.

I'm not particularly happy with this solution, **so I am happy to iterate on it based on suggestions**.

I will now lay out the issues with solving this problem.

### The problem with the code as-is
- `ValidatorStore.validate` inspects every chunk. If it is valid, it will call its `deliveryCallback` should it be defined.
  - This will be called for every chunk even if it is already in the store, which is undesirable.
  - This also will be called for chunks which are not content-addressed, which is useless.

### Implementation issues
- To validate only content-addressed chunks, moving the callback to the content-addressed validator seems like a good idea, but the problem is that the content-addressed validator cannot access the store to check if the chunk is already present.
- Additionally, the `ValitadorStore.validate` func returns `true` as soon as _one_ validator is successful. This means that if the content-addressed validator is further ahead in the array, no callback will be executed—this is obviously a problem.
  - splitting the store `validators` field into 2 fields (one for the content-addressed validator and one for the rest of them) seems like a very unclean solution to me.
    - moreover, type-checking validators to find a `ContentAddressValidator` introduces an import cycle problem.
 
### Solution
- Replace `pss.Deliver` func  with a deliver func constructor.  This will be called in the `NewSwarm` func, which has access to both:
  - the store to check already-present chunks.
  - the validator to check if the chunk is content-addressed.
- This `NewDeliverFunc` will construct a func which does what `pss.Deliver` used to do, but with the additional condition-checking before unwrapping and delivering the trojan message.

### Solution drawbacks
- The store callback will _still_ be called for every valid chunk, even if it is already present or not content-addresed. But it won't actually execute the repair func registered as a handler for the topic if the chunk is not content-addressed or already in the store, because the new dynamically-constructed `Deliver` func takes care of checking these conditions.

closes #2163

### CODE REVIEW

**Comment by zelig** [comment]
@mortelli I think we overcomplicate this.
First of all, we need to decide on required behaviour.
Do we want pss to callback the handler every time a message is received or just once when it is first stored. I think the latter,  which means the validator is clearly not the right place to put the deliver call.
Not exclude chunk which are not content addressed, the validator could just annotate the type on the chunk structure and thats it.
But to be honest the topic/integrity checker is almost as cheap as looking up a field so i would not even bother with this issue, honestly

**Comment by mortelli** [comment]
> Not exclude chunk which are not content addressed, the validator could just annotate the type on the chunk structure and thats it.
> But to be honest the topic/integrity checker is almost as cheap as looking up a field so i would not even bother with this issue, honestly

to clarify, just in case: i am not trying to implement a topic/integrity checker, just restrict the trojan callback to content-addressed chunks.

the place i know in the code where we deal with content-addressed chunks is when the content-addressed validator is called. 

having said that, i am certainly open to alternative implementations, such as the one you mention of annotating a type or looking up a field. i see some issues with this idea though, but i am happy to discuss it further. 

let's put this issue on hold while we continue with the main implementation and set up a call

**Comment by mortelli** [comment]
i am once again opening this PR up for review, after having obtained some results from manual global pinning tests.

in the regular `global-pinning` branch, global pinners **are crashing** after feed updates are submitted:

```shell
panic: runtime error: slice bounds out of range [:23871] with capacity 97

goroutine 516 [running]:
github.com/ethersphere/swarm/pss/trojan.(*Message).UnmarshalBinary(...)
	github.com/ethersphere/swarm@/pss/trojan/message.go:238
github.com/ethersphere/swarm/pss/trojan.Unwrap(0x1385f80, 0xc0135a6a80, 0x1, 0x135e480, 0xc0134697a0)
	github.com/ethersphere/swarm@/pss/trojan/message.go:127 +0x1cf
github.com/ethersphere/swarm/pss.(*Pss).Deliver(0xc00019a600, 0x1385f80, 0xc0135a6a80)
	github.com/ethersphere/swarm@/pss/pss.go:115 +0x4d
created by github.com/ethersphere/swarm/chunk.(*ValidatorStore).validate
	github.com/ethersphere/swarm@/chunk/chunk.go:323 +0xe1
```

this is due to the fact that **valid** feed-related chunks are being processed by a global pinner node, and then inspected for trojan content.

despite not being content-addressed, `Unwrap` is still called on these feed chunks. said function will interpret the first 2 bytes as the length of the payload as if they were regular chunks, but these bytes contain other information.

when attempting to put the payload into a trojan message structure—using its supposed end index derived from the first 2 bytes of the chunk—an out-of-bounds error will occur, causing a `panic` which will then shut down the node.

it's worth noting that this error is not occurring in the `global-pinning-condition-trojan-callback` (the branch for this PR) under this same scenario.

i think the severity of this problem has become apparent, and it is time for a solution to be implemented to prevent further crashes in the global pinners.

@zelig if you are not a fan of this implementation, we can now discuss the alternatives you brought up in your last comment, or others we might come up with.

**Comment by mortelli** [comment]
as discussed with @zelig and @santicomp2014 on 23/5/20, an alternative—cleaner, and less redundant-—solution to this problem has been proposed in #2191.

**Comment by mortelli** [comment]
closed in favor of #2191

**Pull request closed without merging**
