### PR TITLE
stream: limit the number of peers we sync with on bin 0

### LINKED ISSUE #1436: investigate kademlia connectivity and suggest peer functionality
Related to: https://github.com/ethersphere/swarm/issues/1396

The way we build our Kademlia table right now is not very well defined - for example in a given deployment we might have a lot peers in bin 0, or very few, for example:

7 connections in bin 0 (network of 20 nodes)
```
➜  ~ kubectl -n tony exec -ti swarm-private-9 -- /geth --exec="console.log(bzz.hive)" attach /root/.ethereum/bzzd.ipc
Defaulting container name to swarm.
Use 'kubectl describe pod/swarm-private-9 -n tony' to see all of the containers in this pod.
INFO [06-08|20:08:15.464] Bumping default cache on mainnet         provided=1024 updated=4096

=========================================================================
commit hash: 53457a1fd
Sat Jun  8 20:08:15 UTC 2019 KΛÐΞMLIΛ hive: queen's address: efb323de97afdaf1d59cff99f239552d0b86864afac696a1d8a765bdbe0850ec
population: 15 (20), NeighbourhoodSize: 2, MinBinSize: 2, MaxBinSize: 4
000  7 2d5f 6006 7408 7090          | 12 2d5f (0) 1d0e (0) 117f (0) 0f53 (0)
001  6 8185 84a6 982f a0e9          |  6 8185 (0) 84a6 (0) 982f (0) a0e9 (0)
============ DEPTH: 2 ==========================================
002  0                              |  0
003  1 f4a2                         |  1 f4a2 (0)
004  0                              |  0
005  0                              |  0
006  0                              |  0
007  1 eefd                         |  1 eefd (0)
008  0                              |  0
009  0                              |  0
010  0                              |  0
011  0                              |  0
012  0                              |  0
013  0                              |  0
014  0                              |  0
015  0                              |  0
=========================================================================
```

vs

2 connections in bin 0 (same network of 20 nodes)
```
➜  ~ kubectl -n tony exec -ti swarm-private-10 -- /geth --exec="console.log(bzz.hive)" attach /root/.ethereum/bzzd.ipc
Defaulting container name to swarm.
Use 'kubectl describe pod/swarm-private-10 -n tony' to see all of the containers in this pod.
INFO [06-08|20:09:15.434] Bumping default cache on mainnet         provided=1024 updated=4096

=========================================================================
commit hash: 53457a1fd
Sat Jun  8 20:09:15 UTC 2019 KΛÐΞMLIΛ hive: queen's address: eefdfe73b0f47187312c1fdcea5377b7668d6f6cbee33c4e4c344475a53e7edd
population: 8 (20), NeighbourhoodSize: 2, MinBinSize: 2, MaxBinSize: 4
000  2 2d5f 5ab8                    | 12 2d5f (0) 1d0e (0) 117f (0) 0f53 (0)
001  4 8185 a0e9 b373 b8ec          |  6 b373 (0) b8ec (0) a0e9 (0) 982f (0)
============ DEPTH: 2 ==========================================
002  0                              |  0
003  1 f4a2                         |  1 f4a2 (0)
004  0                              |  0
005  0                              |  0
006  0                              |  0
007  1 efb3                         |  1 efb3 (0)
008  0                              |  0
009  0                              |  0
010  0                              |  0
011  0                              |  0
012  0                              |  0
013  0                              |  0
014  0                              |  0
015  0                              |  0
=========================================================================
undefined
```

The number of connections are supposed to be within the range `MinBinSize: 2, MaxBinSize: 4`, but this doesn't work and we've known that for a while.

This is problematic, because half of the chunks for a given upload would end up in bin 0, so once we trigger a retrieve request, we will be making requests for 1/2 of all chunks to our peers in bin 0. If we want to support larger files in Swarm (100MB ... 100GB), as defined in our active Epics, this won't be feasible with only a small number of peers.

-----

At the same time our current implementation establishes syncing with all peers, meaning that if we have a lot of peers in bin 0, we would be syncing 1/2 of our chunks with all of them - which seems to be a lot of waste... we should make an effort to sync content in Swarm without spamming the whole network.

-----

Because of the issues above, I suggest we review our Kademlia functionality and current implementation and discuss and maybe implement something along the lines of:
1. Make sure we have a lot of peers in bin 0, as they are responsible for retrieve requests for half of the chunks on any given download, and we should run fetch requests to all of them. For example, if we are supposed to fetch a 4GB file in a timely fashion, then 1/2 * 4GB == 2GB chunks will be retrieved from bin 0 peers, then we need at least 10 peers for bin 0, in order to deliver adequate user experience.
2. Make sure we don't establish syncing with all our peers in a given bin (and bin 0), but only to a small number K, where K is 3-4 (this exact value is TBD).

In general I think if we have N peers in bin 0, then N should be around 1/2 of all our peers, and probably 1/2 of the `maxpeers` setting. Peers in bins 1..16 should probably be 1/2^(bin_number+1) * maxpeers.

cc @acud @zelig @homotopycolimit

### PR DESCRIPTION
**Pull request by acud**
This PR aims to limit the number of peers with sync with on bin `0` using a semaphore

fixes https://github.com/ethersphere/swarm/issues/1436

### CODE REVIEW

**Review by janos — APPROVED** [review]
LGTM

**Review by holisticode — COMMENTED** [review]
1. Why limit the number of peers only in bin 0, and not, say also in 1, or - maybe all bins < depth?
2. The description of the PR says it's about limiting the number of peers in bin 0 but does not specify how it does that. One has to go through the code.

Maybe it has been discussed in private and is known to the author(s), but as I have been invited to review, I am missing this information, and I had to go through the code.

But what I can see from the code is that actually only *concurrent* `InitPeer` calls are limited, but I understand `InitPeer` to run quickly, and is only meant to establish subscriptions. So, after 3 `InitPeer`s have run, there is no blocking for other peers, which means they end up in the kademlia in bin 0 anyway, so I don't understand what we really are limiting here - just so that there are not too many concurrent `InitPeer`s ?

**Comment by acud** [comment]
> 1. Why limit the number of peers only in bin 0, and not, say also in 1, or - maybe all bins < depth?

Bin `0` represents the most potential syncing overhead from all bins. It incurs the highest traffic and it is trivial to implement, since its incurred bandwidth and localstore congestion _does not depend on depth_. Once you put depth into the equation, you're going to end up with a separate component orchestrating connections and making sure that when the depth changes - the appropriate peers are being synced to. I find this complex to implement and test and so I went for the trivial solution at the first iteration so that people can use Swarm and not incur so much traffic and storage congenstion every time they upload something.

> 2. The description of the PR says it's about limiting the number of peers in bin 0 but does not specify how it does that. One has to go through the code.

The PR description says:
> This PR aims to limit the number of peers with sync with on bin 0 using a semaphore

And that exactly what it does. Limits the number of peers we sync with on bin 0 using a semaphore, which is exactly what I added (a semaphore).


> But what I can see from the code is that actually only _concurrent_ `InitPeer` calls are limited, but I understand `InitPeer` to run quickly, and is only meant to establish subscriptions. So, after 3 `InitPeer`s have run, there is no blocking for other peers, which means they end up in the kademlia in bin 0 anyway, so I don't understand what we really are limiting here - just so that there are not too many concurrent `InitPeer`s ?

@holisticode the buffered channel acts as a semaphore. When a peer that has `po 0` is added and the protocol run function is called - `InitPeer` would eventually be called. Then, once the `if` condition that checks the po of the peer is hit and we end up in the block that adds an element into the buffered channel, after 3 peers with po 0 that are added, the buffered channel will be full, and _further_ peers with po 0 will _block_ on the select case because the buffer is full:
```go
	if po == 0 {
		select {
		case s.binZeroSem <- struct{}{}:
		case <-p.quit:
			return
		case <-s.quit:
			return
		}
		defer func() { <-s.binZeroSem }()
	}
```

Because of the `defer` statement, when a peer is therefore disconnected at an unspecified time in the future - a slot in the buffer will be freed and an arbitrary next peer that was blocking on the `s.binZeroSem <- struct{}{}` line will be scheduled, allowing that peer to start syncing data to the current node.
If the `po` is larger than `0` then we don't block at all and continue execution normally.
This obviously does not cater for the edge case that all peers are in bin 0 or that the node depth is constantly zero but I don't think we should cater for these use cases anyway.
I hope this is now clearer and if there's any other issues with this please do tell

**Comment by holisticode** [comment]
> Because of the defer statement, when a peer is therefore disconnected at an unspecified time in the future 

What I am saying is that it seems to me that "unspecified time in the future" does only apply if the function for subscription is running as a loop until it disconnects. I thought it was a function which would just establish subscriptions and then return right away (as the `InitPeer` name suggests), which would trigger the `defer` and thus the channel would be freed again.

So it really depends on the subscription function I guess.

To be honest, I am not so much of a fan of this type of blocking, because all peers exceeding the max number of peers in bin 0 (3) will block, and thus unnecessarily use up resources until, at some "unspecified time in the future", one peer would disconnect.

**Comment by acud** [comment]
> To be honest, I am not so much of a fan of this type of blocking, because all peers exceeding the max number of peers in bin 0 (3) will block, and thus unnecessarily use up resources until, at some "unspecified time in the future", one peer would disconnect.

Which resources are we talking about? a `Peer` struct entry in the registry? I don't think this is a big price to pay.
Besides, the whole point is to block because you want to be connected to this peer - because you want to be able to send this peer a retrieve request or to potentially have that peer sync from you, you also might want to have the peer send retrieve requests to you.

This method of blocking allows you to connect to a peer and have that peer to function correctly with all other protocols except for syncing (other streams in the stream protocol would potentially work uninterrupted in this manner). So you can maintain connectivity with the peer and select when to sync with it without having to connect to it.

If you have any better solutions I'm happy to hear them out and implement them gladly

**Review by zelig — APPROVED** [review]
this is a hack, dont like
do we really need it?

**Comment by acud** [comment]
i would not PR it if we would not need it :/

**Pull request merged**
