### PR TITLE
swarm/network: bump up bzz protocol version to 4, because of BMT hashes

### PR DESCRIPTION
**Pull request by nonsense**

### CODE REVIEW

**Review by janos — COMMENTED** [review]
I think that `swarm/network/stream.Spec.Version` needs to be incremented to 4.

**Comment by nonsense** [comment]
@janos wouldn't then the BZZ handshake be successful, and a peer being added that we can't do anything with?

**Comment by janos** [comment]
If both bzz and stream protocols are bumped, then it should be fine?

**Comment by nonsense** [comment]
Both `bzz` and `stream` is definitely fine, but `bzz` alone is enough as well. Not sure from a consistency perspective if we want to bump up `stream.Spec.Version` as well.

**Review by janos — APPROVED** [review]
Thanks @nonsense. As you explained, it appears that bzz version change enough. 👍

**Pull request merged**
