### PR TITLE
Add swarm guide to /docs

### PR DESCRIPTION
**Pull request by skylenet**
Imported from ethersphere/swarm-guide (`master@1f8d30f`) 

Todo after merging: 
- [x] On the readthedocs admin page for the `swarm-guide` project, change Repository URL to `https://github.com/ethersphere/swarm`
- [x] Archive ethersphere/swarm-guide ?

### CODE REVIEW

**Comment by nonsense** [comment]
I personally suggest deleting `swarm-guide` after the guide is moved, rather than archived.

**Review by nonsense — DISMISSED** [review]

**Comment by acud** [comment]
agree with @nonsense about `swarm-guide`. reduce clutter. erase. obliterate.

**Comment by acud** [comment]
@skylenet why do we need to commit the build files into the repo? they should be generated on a build hook and published somewhere. i don't see any reason why they should be here. only sources

**Comment by skylenet** [comment]
> @skylenet why do we need to commit the build files into the repo? they should be generated on a build hook and published somewhere. i don't see any reason why they should be here. only sources

wow. good catch! `cp -r *` was a bad idea.

**Comment by skylenet** [comment]
@acud I've deleted the build dir and also created a `.gitignore` to exclude the build dir.

**Review by holisticode — APPROVED** [review]
LGTM! Thanks for this, did you also already check how the deployment works? Will the automatic deployment still work after we merge?

**Comment by holisticode** [comment]
@nonsense there was something which looked like a refresh button, but it actually means "re-request review", that is then what happened and a review has been re-requested to you :) sorry for that.

**Comment by skylenet** [comment]
https://swarm-guide.readthedocs.io/en/latest/ is now using the source from `ethersphere/swarm`. 

I've also moved recent issues from the `swarm-guide` to the `swarm` repo and labeled them with `area:docs`.

For now I've archived the `swarm-guide` repo. And will delete it "soon".

**Pull request merged**
