### PR TITLE
swarm/api/http: cleanup and refactor the http package

### PR DESCRIPTION
**Pull request by acud**

### CODE REVIEW

**Comment by lmars** [comment]
@justelad I know this is WIP, but what specifically do we gain by splitting this into packages? I'm not sure spreading the HTTP code around in different packages is a net benefit to be honest.

**Comment by acud** [comment]
@lmars we've discussed a cleanup in the `http` package on the team level for some time. i'm trying to take a pick at doing this. pulling it into different packages might not give a performance boost, but it would definitely speed up trying to find something in a spaghetti ball of more than a 1000 lines long that just keeps getting more additions and no deletions.

**Comment by acud** [comment]
@lmars i'd be interested to know what are the arguments *against* moving things around into their own packages (which reside within the http package)

**Comment by lmars** [comment]
I understand the current code is a little hard to navigate, but I think the solution is to have some form of route registration in one place, and then individual methods on the `Server` type which represent the different functions of the server.

For example, if you think about handling `bzz-raw` requests, there are two actions:

1. if it's a GET request, get the file at path and serve it
2. if it's a POST request, upload the request body and return the hash

This translates roughly to:

```
func (s *Server) initRoutes() {
	s.Handle("GET", "bzz-raw", s.HandleGetBzzRaw)
	s.Handle("POST", "bzz-raw", s.HandlePostBzzRaw)
}

func (s *Server) HandleGetBzzRaw(w http.ResponseWriter, r *http.Request) {
	//
}

func (s *Server) HandlePostBzzRaw(w http.ResponseWriter, r *http.Request) {
	//
}
```

This gives us a single place to see how the server handles all requests, and from there dig into the individual methods.

This is the approach taken in the `p2p/simulations` package [here](https://github.com/ethereum/go-ethereum/blob/master/p2p/simulations/http.go#L273-L741).

WDYT?

**Comment by acud** [comment]
@lmars introducing routing was exactly the next step i was about to take after breaking down the functionality by context. 

but i do think that having the handlers in the appropriate files which isolate them properly is the right approach, whereas shared methods could be grouped into helpers.
this way, `bzz.go` would look like:
```
func (c *Controller) Get(w http.ResponseWriter, r *http.Request) {
	//
}

func (c *Controller) Post(w http.ResponseWriter, r *http.Request) {
	//
}
...
```
and `bzz-immutable` would look like:
```
func (c *Controller) Get(w http.ResponseWriter, r *http.Request) {
	// do something
}

func (c *Controller) Post(w http.ResponseWriter, r *http.Request) {
	// return HTTP 405 - Method Not Allowed
}
...
```

initializing the routes would be in `server.go` as you suggest. even if you introduce routing the file will stay around 1000 lines of code. the idea also with introducing a controller base type is that we can clean up all of those inlined counters and pull them out to wrapper methods, where you could introduce metrics on the envelope layer without polluting logic. that's my view of how it should be anyway.

what about possible partial http support for pss? publishing local node information for external dapps or even for our own CLI, other utility routes that were already conceived but never implemented, such as disk usage and interaction with localstore size by http interface. you wanna see all of those in one file?

**Comment by lmars** [comment]
@justelad I think the source of our disagreement is that I think it's fine for a file to have 1000 lines of code, provided that code is well structured and readable. I say this because, even if you split it over 10 100 line files, there is still 1000 lines of code (and in fact there is now slightly more code to account for it being in separate files).

For example, [`http.go`](https://github.com/ethereum/go-ethereum/blob/master/p2p/simulations/http.go) in the simulations package is 741 lines of code, but all methods are appropriately named with comments, I'd see no reason to split that out into different files / packages.

Also, in case you don't already, if you find yourself scrolling through files to find things, I'd suggest looking into some tools that will help you (e.g. [`guru`](https://docs.google.com/document/d/1_Y9xCEMj5S-7rv2ooHpZNH15JgRT5iM742gJkw5LtmQ/edit) is pretty useful, I use it via [`vim-go`](https://github.com/fatih/vim-go) and `:GoDef` is a godsent).

**Comment by acud** [comment]
> I think the source of our disagreement is that I think it's fine for a file to have 1000 lines of code, provided that code is well structured and readable.

agree, but regretfully i won't go off my tree. i think that long files are tiresome to work with, and unreasonably painstaking when on-boarding (especially for open source contributors that would like to contribute on their free time).

i'm an IDE kiddie myself so i keep in view possible plugin constructs that allow for easier navigation of code. i don't think that they should, however, constitute as justifications of code structure decisions. 

my argument is that the fact that the entire http logic sits in one file is the main reason it got to its current condition in the first place (people just keep on chucking more code in there with a `server` context; pretty general i would say).

my suggestion to get out of this deadlock: let me do the refactor, clean it up, compact it within different files. and if you still don't like it i would gladly merge it into one, very long, beautiful file (and inline all of the html templates there, too 😄).

**Comment by lmars** [comment]
@justelad 

> my argument is that the fact that the entire http logic sits in one file is the main reason it got to its current condition in the first place

I disagree. The reason the file is the way it is is because it did not start with a well designed structure. It should have had routes and handlers from the start, but it started as [a big switch statement](https://github.com/ethereum/go-ethereum/blob/4d300e4dece56535f56ccc32330340ce89e42581/swarm/api/http/server.go#L71-L236).

This is not to point fingers, it is natural in early code to do this. I [made some changes](https://github.com/ethereum/go-ethereum/commit/71fdaa42386173da7bfa13f1728c394aeeb4eb01#diff-ed5bca01a3a17a09f67d75e3e2fd4ab4) to move towards the handler approach and extract functionality out into different places (e.g. manifest updating into `swarm/api/manifest.go`), but I just didn't have time to take it to its conclusion.

> and if you still don't like it i would gladly merge it into one, very long, beautiful file (and inline all of the html templates there, too 😄).

I think you are taking my comments to the extreme.

What I am proposing is that the routes that are handled by the server, and the handler methods themselves are all contained in one place. If you want to know the functionality of the Swarm HTTP server, go to the `swarm/api/http` package and you will see all the routes and the handlers.

I am not proposing to put _everything_ in this file, the HTML templates are already in a different file ([I put them there](https://github.com/ethereum/go-ethereum/commit/71fdaa42386173da7bfa13f1728c394aeeb4eb01#diff-c54170f9d8f6485df12df44034c81cb4)), and that is a good thing, but they are referenced in the HTTP handlers in the main file because they are part of the functionality of handling HTTP requests.

In this PR, you are introducing a Controller interface, with each controller implementing things like `Get` and `Put`. Taking this to the logical conclusion, if I want to know the functionality of the Swarm HTTP server, I will now just see a generic Controller in the `swarm/api/http` package and then need to go browsing round a bunch of `controller` packages / files to get a sense of what is going on. I don't feel like this is a net benefit in terms of making the code much more clearer and readable.

**Comment by acud** [comment]
@lmars trying to tackle the clean-up in the file but hitting some limitations since the `httprouter` package expects a certain handler method signature.

we are currently extending the `http` package's Request struct with our own metadata (ruid, api.URI). 

This will have to go away since it won't fly with the router (the code inside the handlers need to access these params for logging and to actually process the request, and i don't want to copy paste this init boilerplate into every handler), so we would have to still create some sort of middleware function that would do the basic init functionality, parse the URI, create a separate struct that would contain those (instead of extending the request object), then, inject this struct into a new context object that would be created inside the middleware, and every time we get to a real handler (e.g. `handleGetList`) we would have to unmarshal this data from the context using the key value.

So we have a problem of centralising and generalising the boilerplate code which is run for each request, but then also passing is to the handlers through this router.
we could also use our own custom written router since we dont really need so much functionality (and its seems this just won't work smoothly).

mainly i'd ask you right now for a specific pattern that you see in mind. i tried hacking away through this thing today without much success. i see a sort of MVC solving this pretty easily, but i can't really visualise the solution you're asking for. if you would like to take a hack at it - try to isolate the handler that handles the GET request for `bzz-list` - that's pretty much the easiest, would be easier to see what you're shooting for.

thanks

**Pull request closed without merging**
