### PR TITLE
swarm/docker: Dockerfile for swarm:edge docker image

### PR DESCRIPTION
**Pull request by nonsense**
Copying `Dockerfile` to `ethereum/go-ethereum`, so that we can automatically build `ethdevops/swarm:edge` on push to `master`.

~Ideally this image should support smoke tests as well, which is currently not the case, hence the `in progress` tag.~

### CODE REVIEW

**Comment by nonsense** [comment]
@skylenet this is building and pushing the `swarm:edge` image to `ethdevops/swarm:edge`. We only have to update the branch to `ethersphere/master` in the pipeline, once this is merged.

**Comment by nonsense** [comment]
I'm not happy that we are duplicating this with https://github.com/ethersphere/swarm-docker , but I prefer this, than having to orchestrate an action to push to another Git repo.

**Comment by acud** [comment]
@nonsense are you going to eliminate `swarm-docker` repo then? maybe use git module if not?

**Comment by nonsense** [comment]
Closing this as it has been opened on `ethereum/go-ethereum` repo.

**Pull request closed without merging**
