### PR TITLE
swarm/api: url scheme bzzh for getting hashes of swarm content 

### PR DESCRIPTION
**Pull request by janos**
This PR implements bzzh scheme as described in issue https://github.com/ethereum/go-ethereum/issues/15238.

This PR can be easily changed to use a query parameter instead of new bzzh scheme.

### CODE REVIEW

**Comment by lmars** [comment]
I believe I managed to overrule the outcome suggested in ethereum#15238 so that we use query params instead of protocols, but I think it was on a call and not added to the issue.

I guess we should make a definitive decision and roll with it, I would still like to see this be query params.

**Comment by janos** [comment]
Hi Lewis, I will implement query params instead bzzh scheme. Should the query be *hash=true* analogously to *list=true*?

As different query parameters, like optional arguments, can be composed, here *hash* and *list*, are mutually exclusive, which of them should have precedence?

Future similar features, where type of response (and content-type) will differ based on query parameters may raise the same question, so the response type may be requested with the value of a specific query param instead of different ones. For example *type=list* and *type=hash*. Name *type* is here just an example, lacking the creativity from my side. This is just a thought about API design. Such change can be backward incompatible with current request handling using *list=true*.

**Comment by lmars** [comment]
> Should the query be hash=true analogously to list=true

To avoid collisions with dapps that may want to use query params, I think we made a decision to namespace them (e.g. something like `swarm.hash=true`).

> As different query parameters, like optional arguments, can be composed, here hash and list, are mutually exclusive, which of them should have precedence?

I think it should return a 400 Bad Request if both are specified, leaving it up to the client to decide what kind of response they want by fixing the params.

> Future similar features, where type of response (and content-type) will differ based on query parameters may raise the same question, so the response type may be requested with the value of a specific query param instead of different ones. For example type=list and type=hash. Name type is here just an example, lacking the creativity from my side. This is just a thought about API design. Such change can be backward incompatible with current request handling using list=true.

Sure, so we could make both the list and the hash response an explicit MIME type, so it could be `content_type=application/bzz-list` and `content_type=application/bzz-hash`.

FYI I also brought this up with the Mist team who agreed query params make more sense: https://gitter.im/ethereum/mist?at=59d64122b20c642429c7f5ee

**Comment by janos** [comment]
The latest commit a different approach to resolve https://github.com/ethereum/go-ethereum/issues/15238 then the solution with bzzh scheme.

The response to request bzz request with swarm.hash=true query parameter
will return the hash of the content that will be otherwise returned without
the query parameter.

Response Content-Type is application/bzz-hash.

All possible error responses are the same with or without the query parameter.

**Comment by gbalint** [comment]
For the note: We decided to use url schemes, see https://gist.github.com/gbalint/ce09ada0bebc38f3a8a3dd2ce6c6299f

**Comment by janos** [comment]
Closing it in favour of https://github.com/ethersphere/go-ethereum/pull/163.

Thank you all for reviews and discussion.

**Pull request closed without merging**
