### PR TITLE
swarm/api/http: Error template restyle

### PR DESCRIPTION
**Pull request by Mistra**
Continuing the discussion from issue #457

screenshot

The result is more or less like this

### CODE REVIEW

**Comment by cobordism** [comment]
Hi. Thank you for this PR.
However you will have to reissue it to another branch.
Now that the swarm-network-rewrite is over and the master PR has been made here: https://github.com/ethereum/go-ethereum/pull/17041
we will begin using master/develop branches again.

I think this will be cleared up in the coming days.

**Comment by Mistra** [comment]
I see, mind keeping it open for a while? I just wanted to keep on discussing about the topic, I don't think that was going to be merged anyway.

**Comment by cobordism** [comment]
sure. we'll keep it open and use this space to talk :)

**Comment by Mistra** [comment]
While we are here, a few things:

1. I've isolated the css under a single constant but it's just a workaround to avoid a bit of copy/paste. Since the error pages are more or less all the same, wouldn't it be better to have a unique html template and pass all the needed variables through the parser? It's the first solution that came into my mind.

2. Some titles and error subtitles are long. E.g. _There was a problem serving the requested page_. Mind if I try to make it more short and to the point?

3. The style is minimal and dark. While minimal could work, maybe dark is not actually the best related to other pages like https://swarm-gateways.net/bzz:/theswarm.eth/
Another mock was this one, maybe is more in tune.
orange theme

**Comment by acud** [comment]
@Mistra thank you for the contribution!
the first one looks great but indeed dark theme is not so user friendly

the second is _really_ orange 😄 
try to tint the background a bit? (let's say with 50% or 20% opacity)
you can hit me up on gitter and we could do a few tests together and see what works best if you have a bit of time. we could also tackle the other issues together.

**Comment by Mistra** [comment]
Closing this one, I'll open a new PR after #756 is complete.

**Pull request closed without merging**
