### PR TITLE
Fix goroutine leak by closing accounts manager on Node.Stop

### LINKED ISSUE #1142: network/simulation: Goroutine leak (simultaneously alive, limit exceeded)
`race: limit on 8128 simultaneously alive goroutines is exceeded, dying`

**How to reproduce?**
`time go test -race -count 100 github.com/ethereum/go-ethereum/swarm/network/simulation... `

**Output**
```
WARN [01-21|14:38:42.366|p2p/simulations/network.go:570]      Can't stop node                          id=c64bb2e7299b3155 err="node not started"
WARN [01-21|14:38:42.370|p2p/simulations/network.go:570]      Can't stop node                          id=6c6cf63e67a108b9 err="node not started"
WARN [01-21|14:38:42.379|p2p/simulations/network.go:570]      Can't stop node                          id=d52b6a5367235153 err="node not started"
WARN [01-21|14:38:42.473|p2p/simulations/network.go:184]      Node startup failed                      id=8011a7c6f6a30768 err="duplicate service: *simulation.noopService"
WARN [01-21|14:38:42.474|p2p/simulations/network.go:570]      Can't stop node                          id=8011a7c6f6a30768 err="node not started"
race: limit on 8128 simultaneously alive goroutines is exceeded, dying
FAIL	github.com/ethereum/go-ethereum/swarm/network/simulation	186.563s
ok  	github.com/ethereum/go-ethereum/swarm/network/simulations	1.070s
ok  	github.com/ethereum/go-ethereum/swarm/network/simulations/discovery	1.102s

real	3m9.438s
user	3m16.485s
sys	0m20.138s
```

### PR DESCRIPTION
**Pull request by janos**
Fixes: https://github.com/ethersphere/go-ethereum/issues/1142

While performing the test described in https://github.com/ethersphere/go-ethereum/issues/1142 issue, a large number of gorutines were created and not terminated. Stack trace shows many goroutines:

```
goroutine 3370 [select]:
github.com/ethereum/go-ethereum/accounts.(*Manager).update(0xc0000b7520)
	/Users/janos/go/src/github.com/ethereum/go-ethereum/accounts/manager.go:95 +0x22a
created by github.com/ethereum/go-ethereum/accounts.NewManager
	/Users/janos/go/src/github.com/ethereum/go-ethereum/accounts/manager.go:68 +0x6f2

goroutine 4481 [select]:
github.com/ethereum/go-ethereum/accounts/keystore.(*watcher).loop(0xc0035ac9a0)
	/Users/janos/go/src/github.com/ethereum/go-ethereum/accounts/keystore/watch.go:94 +0x65b
created by github.com/ethereum/go-ethereum/accounts/keystore.(*watcher).start
	/Users/janos/go/src/github.com/ethereum/go-ethereum/accounts/keystore/watch.go:52 +0xb6
```

Accounts manager is created but not closed for node.Node, leaving large number of goroutines alive. This change closes accounts manager on Node.Stop, but Node initializes accounts manager in constructor, not no Start, so for Restart and Start to work as expected, accounts manager construction and closing is handled in Start as well, preserving the original required initialization in constructor.

Keystore watch creates fs watchers and we have noticed before a lot of `(FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)` errors on macOS while running a large scale simulations. This change may improve simulations performance as it closes unneeded file watchers.

Note: Running tests described in https://github.com/ethersphere/go-ethereum/issues/1142 `time go test -race -count 100 github.com/ethereum/go-ethereum/swarm/network/simulation` require changes from PR https://github.com/ethereum/go-ethereum/pull/18464 to fix race conditions, but this PR solves goroutine leak. This tests run for about 20 minutes.

### CODE REVIEW

**Review by frncmx — APPROVED** [review]
lgtm :+1:

**Comment by frncmx** [comment]
@janos I think in the upstream PR we should request a review from Felix and Peter, as I see they worked on this part mostly. That can take time, too.

So what do you think about submitting this upstream?

**Comment by janos** [comment]
@frncmx yes, I'll submit upstream, to speed things up.

**Comment by janos** [comment]
Submitted upstream https://github.com/ethereum/go-ethereum/pull/18505.

**Pull request closed without merging**
