### PR TITLE
pss: Make digest independent of RLP

### LINKED ISSUE #1688: pss: Make digest independent of RLP
Currently we are using the RLP serialization for creating digests of messages  (see `pss/types.go:(*PssMsg).serialize(...)`)

This serialization should however be independent of underlying serialization and p2p transport, in case we need to use it for other purposes on the network in the future.

### PR DESCRIPTION
**Pull request by aperonam**
Replaced RLP encoder, used to serialize pssMsg for digesting, with golang's gob encoder

closes #1688

### CODE REVIEW

**Review by nolash — COMMENTED** [review]
Isn't gob intended for go-types? If so, I don't believe we need the extra artifacts.

**Comment by aperonam** [comment]
Ok, I'll change it to not use gob encoder,  perhaps just doing a sprintf of a struct with the msg.To field and the msg.Payload hash (whisper envelope hash)

**Comment by nolash** [comment]
I'm thinking this has to be changed anyway when we remove the whisper stuff. Maybe it's not worth the bother doing it before. Perhaps also we should introduce salt in the (new) message type, too. Maybe we should talk this out some more.

**Comment by jpeletier** [comment]
I think we should close this. I got rid of the serialize method entirely as part of #1734, since it was only being used to calculate a digest for a cache key (now there is a new `Digest()` method that gives you a quick Keccack256 hash of the message without using RLP).

If we need to serialize/deserialize this structure at some point, we should write that code then and implement the right interface, e.g. `encoding.BinaryMarshaler/Unmarshaler` , etc.

**Pull request closed without merging**
