### PR TITLE
swarm/storage: File hasher correctness implementation

### PR DESCRIPTION
**Pull request by nolash**
This PR introduces the file hasher, which calculates the file hash of a synchronous byte stream. It uses a pool of asynchronous BMT hashers to generate individual chunk hashes. Data is written directly into the hash buffer from the caller code, in segments equal to hash digest size (32). When a full chunk has been written, it is automatically and asynchronously hashed, and the hash key and written to the corresponding position in its parent chunk.

It also introduces a filehasher reference implementation, that replaces the TreeHasher/PyramidHasher as source of truth for correctness checking.

NOTE! The tests may hang depending on the size of the BMT tree pool.

The scope of this PR is to create a _correct_ implementation of the file hasher. The following PR will _optimize_ the implementation.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 88f57c0562d287d9f1f37cd064ddddef456a2538
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: d64084834db3ec1d775072974995806d94025fa0
  * Your commit message body contains a line that is longer than 80 characters

Guidelines are available at https://github.com/ethersphere/go-ethereum

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 88f57c0562d287d9f1f37cd064ddddef456a2538
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: d64084834db3ec1d775072974995806d94025fa0
  * Your commit message body contains a line that is longer than 80 characters

Guidelines are available at https://github.com/ethersphere/go-ethereum

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 88f57c0562d287d9f1f37cd064ddddef456a2538
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: d64084834db3ec1d775072974995806d94025fa0
  * Your commit message body contains a line that is longer than 80 characters

Guidelines are available at https://github.com/ethersphere/go-ethereum

---
This message was auto-generated by https://gitcop.com

**Comment by nolash** [comment]
obsoleted by https://github.com/ethersphere/go-ethereum/pull/969

**Pull request closed without merging**
