### PR TITLE
cmd/swarm-smoke: smoke tests for the test cluster

### PR DESCRIPTION
**Pull request by nonsense**
This PR is an effort to create a bit more tooling to test local and remote clusters as a black box, and trigger failure scenarios that we don't see with the regular test suite. https://github.com/ethersphere/go-ethereum/issues/340

This is adding a cmdline tool `swarm-smoke` which currently supports only one command: `upload_and_sync`.

It uploads a random file to 8501, sleeps for 10 seconds, and then tries to download it from all endpoints 8501-8512. If the HTTP request fails, it tries again after 10 seconds.

It is not yet suitable for automated testing, but is handy when running it manually.

### CODE REVIEW

**Comment by nonsense** [comment]
A few bugs that I encountered using this tool:
1. When we upload a 50MB file, it appears that nodes are responding with 200 OK, before the file has finished syncing up on the given node:
```
TRACE[03-30|19:06:24.640387|swarm-smoke/upload_and_sync.go:77] http get response                        ruid=1fd89f5b api=http://8509.testing.swarm-gateways.net hash=11b5487b5d307c10d940d9e4aa05643fa00c82a428d76ec9027245add31f834c code=200 len=50000000
WARN [03-30|19:06:28.841038|swarm-smoke/upload_and_sync.go:89] unexpected EOF                           ruid=1fd89f5b
```

For example, try running the following command, and notice how we get errors for ~1-2minutes, but after that file is retrieved successfully:
```
swarm-smoke --filesize 50 --bzz-api http://8504.testing.swarm-gateways.net c
```

2. `MemStore.removeOldest` is reaching the if-blocks that have `panic(nil)` - we should understand how this is possible and refactor out the panics.

3. Sometimes we get 502 response code on HTTP GET requests - not sure if this is an Nginx error, or a Swarm error, we should investigate further.

**Review by zelig — COMMENTED** [review]
@nonsense this is what the network simulation framework is for. 
I want to write scenarios using that. 

Plus this is adding only http API to @janos's test right?

**Comment by nonsense** [comment]
@zelig the simulation framework currently does not work with remote nodes. This is just a quick hack/experiment to have a simple automated test, until we have these features part of the simulation framework, rather than having us perform them manually.

I am also thinking that we would need an utility to run continuously and start different simulations on a running cluster - I am sure many of the failures we will see will be visible only after the clusters accumulate data for a while, and have been running for a while, rather than spinning up new clusters all the time.

**Review by zelig — APPROVED** [review]

**Review by janos — APPROVED** [review]

**Comment by nonsense** [comment]
Merging as the red X is not due to this PR.

**Comment by nonsense** [comment]
2. is addressed by https://github.com/ethersphere/go-ethereum/pull/363 - changing the impl. of `MemStore` from our in-house mem hash tree, to a LRUcache by hashicorp.

**Pull request merged**
