### PR TITLE
swarm/network: bump versions for protocols bzz, hive and stream to 3

### PR DESCRIPTION
**Pull request by janos**
Raise version for bzz, hive and stream protocols to 2 in order not keep off older nodes.

### CODE REVIEW

**Comment by nonsense** [comment]
@janos maybe a stupid question, but what about `protocol.go:191`? `hive` version 1.0?

**Comment by janos** [comment]
@nonsense Yes, that looks that it should be incremented, too. Protocol version and RPC versions have different form and usage. @zelig should we set hive RPC version to 2.0?

**Review by zelig — APPROVED** [review]

**Comment by zelig** [comment]
> should we set hive RPC version to 2.0?

@janos maybe all versions protocol and rpc should be 3 as in POC3 eventually

**Comment by janos** [comment]
@zelig right, 3.0 would make more sense. The PR is updated.

**Review by gbalint — APPROVED** [review]

**Pull request merged**
