### PR TITLE
bzz-script: self-validating chunks

### PR DESCRIPTION
**Pull request by jpeletier**
# Abstract

This PR introduces **bzz-script**, a generalization of the signature-based validation present in Swarm Feeds that provides user-configurable self-validating chunks. Among other things, it enables multi-signature feeds of all kinds and a number of other scenarios. Fasten your seatbelt and enjoy the ride!

# Background

## Validators in Swarm

All data chunks flowing throughout the Swarm network must comply with validation rules that enforce a relationship between the chunk address and the chunk data. If a chunk arrives to a node that does not conform to these rules, the chunk is discarded. Potentially, the node where that chunk came from could be ignored and/or disconnected, so every node has to make sure the chunks they pass on to other nodes are compliant.

In order to abstract this concept, Swarm introduced the concept of *Validators*. A Validator is a struct that implements this simple interface:

```go
type ChunkValidator interface {
	Validate(chunk Chunk) bool
}
```

So basically: *here is a chunk, tell me if it is good or not*.

Validators can be stacked, meaning that if there is more than one, Swarm will ask each validator if it would stake its life for each chunk that comes in. If no validator returns `true`, the chunk is discarded mercilessly. Otherwise, the chunk is given a warm welcome, stored and forwarded.

### The Content-Addressed Validator

When Swarm was first launched, it only needed one basic validation rule, which is that for every chunk, its address must be the hash of the content it carries:
```
address == H(content)
```
This allows anyone to produce and upload any content without conflict in the address space, since in practicality there cannot be two different pieces of content that produce the same hash and for that reason have the same address. For every chunk, coming from the local user or remote nodes, Swarm will execute that function and determine whether to keep and forward or to drop it.

However, forcibly, new content means a new address for it&ndash;Swarm at the core is a content-addressed network. So, to update users on new content, you have to find a way to publish the address of your new content.

## Swarm Feeds Validator

So we need a way to keep the address fixed to a certain degree while at the same time making sure there is some level of control over chunk addresses to avoid users producing conflicting ones.

Having the possibility of adding different validators opened the door for adding a new, interesting validator that made Swarm Feeds possible. In a simplified form, it looks like this:

```
address == H(user|topic) && recover_signer(signature) == user
```
Where: 
* `user` is the Ethereum Address of the user
* `signature` is calculated as `signature = sign(address | content, user_private_key)`
* `topic` is an arbitrary string.
* `sign()` is a function that calculates the ECDSA signature of some data, provided a private key.
* `recover_signer()` is a function that validates an ECDSA signature and retrieves who signed the message or fails.

First of all, given that `address == H(user|topic)`, we can be certain that *users have their own address space*, meaning that two different users cannot share the same chunk address for their content. 

Second, this validator has very interesting properties: For these chunks, **`address` is no longer derived from the content**, as opposed to the `ContentAddressValidator` described above. The direct consequence is that we can have a **fixed address** that points to content that can potentially change. (Having content changes throughout Swarm in an orderly fashion, though, is another story and a new, time-based component, the `Epoch` needs to be added to the address. Check out [Adaptive Frequency](https://github.com/ethereum/go-ethereum/pull/17559) in Feeds) for details on this), but for now let's continue assuming this is not an issue. 

### Analyzing Swarm Feeds' validator

Breaking down the above validator expression, we distinguish the following three things:

1. A challenge, stating "This chunk, with this address can only be created by Alice", namely:
```
address == H(alice|topic)
```
2. A response to that challenge, also contained in the chunk. A signature that proves that indeed Alice has created this chunk:
```
recover_signer(signature) == alice
```
3. the actual **content** to be stored under the above `address` in case the challenge is responded appropiately. The signature covers the content as well.

Thus, if Bob knows Alice's Ethereum address and they both agree on a `topic`, Bob can derive a chunk address by calculating `H(alice|topic)`, query Swarm for a chunk with that address and be certain that the retrieved content, if any, was actually authored by Alice. Bob can be sure because the Feeds Validator, running in his personal node has enforced the above rule and verified the signature, or discarded the chunk.

This works well, and a number of applications are already taking off, such as [Ethergit](https://www.ethergit.io) and [Mainframe](https://mainframe.com), leveraging Feeds to publish changing content on Swarm. There are some limits, however, which is that this challenge / response mechanism with exactly one-user signature verification is harcoded in Swarm. There is no way to have Swarm validate things differently without actually changing Swarm code and opening a PR.

What if we would like to allow that certain content be updated by 2 or 3 different people independently? or enforce that exactly 3 out of 5 people signoff on a given content change? or even prove that some computational work has been done in order to avoid spam?

...Enter bzz-script

# bzz-script

We saw before that an incoming Feeds chunk contains three things:
1. A challenge that must be responded. **The chunk address is derived somehow out of this challenge description**.
2. A response to that challenge, i.e., some sort of proof that the challenge has been overcome. 
3. The actual content to be accepted and stored under that address if the response above indeed fulfills the challenge.

Thus, a generic validator would look as follows:
```
address == H(challenge) && (proof that the challenge is fulfilled)
```
If we want to be able to have a certain degree of freedom in describing different types of challenges and their responses, we need some sort of language to encode them so Swarm can quickly verify if a chunk must be accepted or dropped. 

Let's pause for a moment, go back in time and take ...

## ... a look at Bitcoin transactions:
A Bitcoin transaction contains the following three things:
1. A transaction input locking some funds describes a cryptographic challenge
2. A response to that challenge, provided by the person willing to spend those funds, who needs to prove ownership of them.
3. An amount that will be transferred if the response above fulfills the challenge.

The Bitcoin protocol defines a simple language, called [Bitcoin Script](https://en.bitcoin.it/wiki/Script) to describe these challenges. It is a very limited, stack-based language that is intentionally not Turing-complete to allow for safely and quickly verifying transactions are valid. In this [link](https://www.mycryptopedia.com/scriptpubkey-scriptsig/) you can learn the details of how a challenge together with the response is verified, but roughly the challenge script (called scriptPubKey) and the challenge response script (called scriptSig) are concatenated and if after executing them the value at the top of the stack is nonzero, the transaction is considered valid and the funds are transferred.

This looks **a lot** like the problem we are trying to solve. The difference is that instead of checking whether funds can be spent or not, we are deciding about allowing a chunk into our node or dropping it.

## Implementing bzz-script

At the heart of bzz-script is a **port of the Bitcoin Script virtual machine**, modified to work with Ethereum addresses and signatures and bereft of Bitcoin-specific code unnecessary for our purposes. It is based on the excellent, proven, battle-hardened [btcsuite/btcd](https://github.com/btcsuite/btcd) go implementation of the Bitcoin daemon, in production since 2013. The port includes a heavy test suite, inherited in full.

With this in our toolbox, we have now a language to describe challenges and responses. For example, the original single-user signature Feeds functionality can be expressed as:

challenge (scriptKey):
```
OP_PUSH_DATA_20 alice OP_CHECKSIG OP_EMBED topic
```
response (scriptSig):
```
OP_PUSH_DATA_65 signature
```
and
```
address=H(scriptKey)
```
Where:
* `OP_PUSH_DATA_20` is a bzz-script opcode that pushes the next 20 bytes on to the stack
* `alice` is Alice's 20-byte Ethereum address.
* `OP_CHECKSIG` is a bzz-script opcode that pops the topmost two items from the stack, expecting an Ethereum address and a signature. It then checks their validity. If successful, the value `true` is pushed on to the stack, otherwise `false` is pushed.
* `OP_EMBED` is a non-executable command that allows to embed some arbitrary data or nonce into the script, like a code comment. Ignore this for now.
* `topic` is an arbitrary string.
* `OP_PUSH_DATA_65` is a bzz-script opcode that pushes the next 65 bytes on to the stack.
* `signature` is the 65-byte Ethereum signature covering the **payload content** we want to allow in together with `scriptKey`, that is, `signature=sign(scriptKey|content, alice_private_key)`

Documentation about the above opcodes and binary encoding can be found in the [Bitcoin Script](https://en.bitcoin.it/wiki/Script) doc page. `OP_CHECKSIG` and `OP_CHECKMULTISIG` have been modified, though, to work with Ethereum signatures. `OP_EMBED` is new. You can read about these opcodes in the reference included below.

When `scriptSig` and `scriptKey` scripts are combined, the resulting program reads as follows:
```
OP_PUSH_DATA_65 signature OP_PUSH_DATA_20 alice OP_CHECKSIG OP_EMBED topic
```

The first two opcodes push the signature and alice's Ethereum address on to the stack, then `OP_CHECKSIG` takes the two topmost items of the stack and checks the signature, putting `true` or `false` back on the stack, depending on whether the signature checks out or not. `OP_EMBED` is ignored.

If `address == H(scriptKey)` **and** the above script indeed returns `true`, we accept the chunk. Otherwise we drop it. Note that the code itself is contained in the chunk. Each incoming chunk can potentially carry a different type of script depending on the application, which opens a world of possibilities.

So we are back to our starting point. Our new bzz-script validator will accept a chunk in if:
```
address == H(challenge) && (proof that the challenge is fulfilled)
```
or, expressed in another way:
```
address == H(scriptKey) && (result of executing scriptSig+scriptKey, true/false)
```

## Caveats

bzz-script does not support content updating. Once you have published content under an address, publishing different content under the same address will have unpredictable results. You could get the first content you published, the last one or something intermediate, depending on what Swarm node you query, when, or how the message actually propagated throughout the network. This behavior happens at the Swarm-chunkstore level, upon which bzz-script is built.

Most importantly, this is also affected by who or how many are able to write to the address according to the challenge you have defined in `scriptKey`: You should use `scriptKey`s that are secure for your application, i.e., include the verification of some proof or signature in order to use them.

To overcome the content updating limitation, you could vary the address (`scriptKey`), so you can somehow generate new addresses in a predictable way and write only once to each. For example, given this `scriptKey` for a simple signature-based challenge:

```
scriptKey: OP_PUSH_DATA_20 alice OP_CHECKSIG
```

You can vary the address by appending a time-based component, namely:

```
scriptKey: OP_PUSH_DATA_20 alice OP_CHECKSIG OP_EMBED <day of the year>
```

Remember `OP_EMBED` does not affect script execution, but does vary the address since `address = H(scriptKey)`... this way, the application looking up your content could generate the correct address by looking at the clock. The above example would work for an application that updates content daily. This varying of the address by incorporating a time-based address derivation is the basis of Swarm Feeds, which I encourage you to use if you want a high level API to mutable content.

## Conclusion

This PR aims to create a versatile layer below Swarm Feeds in order to cover most mutable content use-case scenarios, putting Swarm in the forefront of decentralized storage with strong support for content updates.

Key to this PR is the realization of how a validator can be generalized as challenge + challenge response, and why it makes sense that the chunk address is derived from the challenge only, as it is with Feeds.

Bringing in the proven Bitcoin Script VM from [btcsuite/btcd](https://github.com/btcsuite/btcd) enables us to augment functionality dramatically in a safe way, without increasing the complexity significantly (the VM is indeed very simple), and also being able to reuse the knowledge and documentation already written about it.

Additionally, functionality can be extended easily by adding VM opcodes as opposed to having to modify Feeds code to support other scenarios.

### Feeds refactoring

Once bzz-script is merged, we can refactor Feeds to make use of bzz-script. This will:

* Allow multi-signature feeds, or feeds based on any type of challenge script.
* Simplify Feeds code, since signature verification and chunk parsing is done by bzz-script. Feeds would focus on the epoch/adaptive frequency lookup algorithm and provide a simple API.

# Final note

I hope you like this new functionality. If you have further questions or comments, you can find me in Gitter, in [#orange-lounge](https://gitter.im/ethersphere/orange-lounge) @jpeletier.

# Reference and examples

The below can be considered preliminary documentation that would go to the Swarm Guide. I encourage you to continue reading since it digs a bit deeper in explaining the work done to make bzz-script a reality.

### `OP_CHECKSIG` and `OP_CHECKMULTISIG`

Both `OP_CHECKSIG` and `OP_CHECKMULTISIG` have been modified to work with Ethereum addresses directly, instead of Bitcoin-style public keys. The original opcodes would work checking signatures against a public key, so more elaborate scripts were needed (pay to script hash, or P2SH) in order to be able to use the simpler Bitcoin addresses. Bzz-script modifies these opcode's syntax so the user can work directly with Ethereum addresses.

The signature digest hash is calculated as: 
```
digest = H(scriptKey|content)
```
Where: 
* `scriptKey` is the chunk's scriptKey challenge, binary encoded.
* `content` is the content this chunk aims to store.
* `H()` is the Keccack256 hash function.

`OP_CHECKMULTISIG` does not have the "[extra value popped from the stack](https://en.bitcoin.it/wiki/Script#Crypto)" bug in bzz-script.

#### `OP_CHECKSIG` syntax

* Input stack: `<signature> <20-byte ethereum address>`
* Output stack: `<result>` (`true` or `false`)

#### `OP_CHECKMULTISIG` syntax:

* Input stack: `<signature 1> .. <signature M> M <address1> .. <address N> N`. Where `M` is the number of signatures required and `N` the number of authorized signers.
* Output stack: `<result>` (`true` or `false`)

### `OP_EMBED`

`OP_EMBED` is a NOP opcode, it does nothing. Its only purpose is to be able to embed arbitrary data into a script. A `scriptKey` with `OP_EMBED` will produce the same result as the same script without these opcodes, but the chunk address will be different since the embedded data will be included to calculate the address, together with the rest of `scriptKey`.

#### `OP_EMBED` syntax:

`OP_EMBED <length> <data>`. Where `length` is 1 byte to specify the length (max 255), followed by `data`, a byte array of that length. 

### `OP_CHECKPOW`

bzz-script includes a simple proof-of-work checking opcode (`OP_CHECKPOW`). With this opcode, a challenge can be included in `scriptKey` to have the user supply a sufficient proof-of-work in order to consider a chunk valid.

The goal of this opcode is to help reduce spam in many-to-one communication, or anonymous-to-one communication by requiring the interested party to demostrate that some level of work has been done in order to publish a given chunk. 

Proofs are considered valid according to this formula:
```
valid == H(nonce|scriptKey|content) < target
```
Where: 
* `nonce` is an arbitrary byte array
* `scriptKey` is the chunk's scriptKey challenge
* `content` is the content this chunk aims to store.
* `target` is a 32-byte number.
* `H()` is the Keccack256 hash function.

#### `OP_CHECKPOW` syntax:

* Input stack: `<nonce> <compact_target>`. Where `nonce` is an arbitrary byte array and `compact_target` is an [nBits-encoded](https://bitcoin.org/en/developer-reference#target-nbits) 32-byte number.
* Output stack: `<result>` (`true` or `false`)

## bzz-script API

The bzz-script API is meant to be a plumbing/low-level API on top of which other layers can be built. Nevertheless, it is exposed as a simple `PUT`/`GET` API as follows for debugging and experimentation:

### Publishing a bzz-script chunk

To publish a chunk, HTTP `PUT` a JSON file like the below to `/bzz-script:/`

```javascript
{
  "scriptKey": {
    "script": "DATA_20 0x5b42a8b24fbddd0a8505148a007bd85f75c63d7a CHECKSIG EMBED 0x1d 0x736f6d6520656d626564646564206461746120696e20746865206b6579"
  },
  "scriptSig": {
    "script": "DATA_65 0xd154279b046e07d0f456ace1a7e98dc7a464e4ea9a88da64aa8e154d9f2ad08b4cc80bd8cfded1055ff6b607e9adf7decf9de385e1db1163dfd5faaf1365efea01"
  },
  "data": "0x68656C6C6F20776F726C6421" // hello world!
}
```
Where:
* `scriptKey` contains the challenge script
* `scriptSig` contains the challenge response
* `data` contains the data we would like to store, hex encoded.

The address under which the data will be stored is calculated as `H(scriptKey)`.

The maximum length of `scriptKey`, `scriptSig` and `data` together can't exceed the chunk size, or `4096` bytes.

Try it:
```sh
curl -X PUT http://localhost:8500/bzz-script:/ --data '{"scriptKey":{"script":"DATA_20 0x5b42a8b24fbddd0a8505148a007bd85f75c63d7a CHECKSIG EMBED 0x1d 0x736f6d6520656d626564646564206461746120696e20746865206b6579"},"scriptSig":{"script":"DATA_65 0xd154279b046e07d0f456ace1a7e98dc7a464e4ea9a88da64aa8e154d9f2ad08b4cc80bd8cfded1055ff6b607e9adf7decf9de385e1db1163dfd5faaf1365efea01"},"data":"0x68656C6C6F20776F726C6421"}'
```

If successful, the chunk address will be output by this call as a simple JSON hex string: `"ed615c46817924faf802a692ec016c9b9c08554543240060f791f73bf6b4cbd5"`

### Retrieving a bzz-script chunk

To retrieve a chunk, simply HTTP `GET` to `/bzz-script:/<address>`. This will recover the JSON as previously posted above.

Try it:
```sh
curl http://localhost:8500/bzz-script:/ed615c46817924faf802a692ec016c9b9c08554543240060f791f73bf6b4cbd5
```

## Interesting scripts

Let's look at some example scripts

### Trivial script example

* scriptKey: `OP_TRUE` (`OP_TRUE` just puts `true` on the stack.)
* scriptSig: (empty)
* content: `hello world!`

This script always returns true. `scriptKey` in this case does not pose any real challenge and thus anyone could post content under this address. Remember that the address is `H(scriptKey)`. In this case, `scriptKey` is just the opcode `OP_TRUE` = `0x51`. The Keccack256 hash of `0x51` is `0xfbf3cc6079e09a6a2a778706898aef91b633ff613801d212e0afe7f411ddb1d2`

Try it:
```sh
curl -X PUT http://localhost:8500/bzz-script:/ --data '{"scriptKey":{"script":"OP_TRUE"},"scriptSig":{"script":""},"data":"0x68656C6C6F20776F726C6421"}'
```

While you can go ahead and store content this way under this address, it is not guaranteed that you or your users will get back the same information: the information you get back will depend on how the published chunk has actually propagated throughout the network. Anyone can post to this address, overwrite your content, or worse: a portion of the users could see your information and another portion see information posted by someone else.

From the point of view of the user querying this address, they will immediately read `scriptKey` and consider it inappropriate or insecure, thus considering the content retrieved as being of dubious origin.

### Multisig script example

The following script describes a 2-of-3 multisig challenge, meaning that any 2 signatures out of 3 authorized users are required to be able to post to this address.

* scriptKey: `2 DATA_20 alice DATA_20 bob DATA_20 charley 3 CHECKMULTISIG`
* scriptSig: `DATA_65 alice's_sig DATA_65 bob's_sig`
* content: `hello world!`

Where `alice`, `bob` and `charley` are their respective Ethereum addresses and `alice's_sig` and `bob's_sig` are Alice and Bob's 65-byte ECDSA signatures over `scriptKey` and the content they want to store.

Try it:

```sh
curl -X PUT http://localhost:8500/bzz-script:/ --data '{"scriptKey":{"script":"2 DATA_20 0xceb358c6606fddb5ad28513938921e66b2fa38dd DATA_20 0x5b42a8b24fbddd0a8505148a007bd85f75c63d7a DATA_20 0x505d59332fd9ebddf84e520f0faa9e3cff16c7f6 3 CHECKMULTISIG"},"scriptSig":{"script":"DATA_65 0x3aaa4390fd9b50ff840ab757f36d83b65281578261b8d9fa8abb843bd3b8fcc740f800982b1192562a35e066818acb1d22c0f60cf21a001b0ea405aad5481fa000 DATA_65 0x236a7d8e3daa8395dba4572156292ffb6e63cdffd095c5caa06fd276c983a5b907ce8881035d15701596bd21e39d7f4a413ade47a642258de557ddd19a7a1e2d01"},"data":"0x68656C6C6F20776F726C6421"}'
```
You will get back the chunk address, `H(scriptKey)`, or `66f862ab0cb170142786ef9e4d321dad46fbf007ed7a0d677a6c54cd377df80e`. You can also try to alter the signatures and check that you'll get a `401 Not Authorized` error instead.

As opposed to the "trivial example" above, users querying this address can analyze the challenge (`scriptKey`) and thus conclude that returned content under this address must indeed be signed off by at least 2 of the 3 authors. If in addition, the combination of `scriptSig`+`scriptKey` checks out, then they can be certain content is authentic according to the challenge.

To retrieve the information back, use the following command:

```sh
curl http://localhost:8500/bzz-script:/66f862ab0cb170142786ef9e4d321dad46fbf007ed7a0d677a6c54cd377df80e
```

### Proof-of-work script example

* scriptKey: `DATA_4 0x1effffff CHECKPOW`
* scriptSig: `DATA_8 0x8f5e010000000000`
* content: `hello world!`

Where `DATA_4` is a bzz-script opcode that pushes the next 4 bytes to the stack and similarly `DATA_8` pushes the next 8 bytes to the stack. `0x1effffff` is an nBits-encoded difficulty target and `0x8f5e010000000000` is the nonce that satisfies the proof of work target.

Try it: 

```sh
curl -X PUT http://localhost:8500/bzz-script:/ --data '{"scriptKey":{"script":"DATA_4 0x1effffff CHECKPOW"},"scriptSig":{"script":"DATA_8 0x8f5e010000000000"},"data":"0x68656C6C6F20776F726C6421"}'
```

You should get the chunk address back: `81353fef8977f117a41769f6c2a13e7082adcc5fe5c6ef16bfce4f676a0741ca`. Thus, to retrieve the information, use the following command:

```sh
curl http://localhost:8500/bzz-script:/81353fef8977f117a41769f6c2a13e7082adcc5fe5c6ef16bfce4f676a0741ca
```

### CODE REVIEW

**Comment by zelig** [comment]
@jpeletier super exciting ,
see linter complaint https://travis-ci.org/ethersphere/go-ethereum/jobs/468805589#L513

**Comment by jpeletier** [comment]
fixed. Let that be the biggest issue with this PR ;-)

**Comment by nagydani** [comment]
This is very impressive work, but the use case for it is not clear and it is far from obvious that the benefits overweigh the added complexity, attack surface and codebase size to be maintained.

Swarm feeds are a lightweight substitute for blockchain-based updates, a scalability aid. In a typical Swarm-based đapp, eventual consistency is achieved through regularly uploading the most recent state of a feed to the blockchain. Thus, a self-validating mechanism should be conducive to being validated by smart contracts as well; the proposed solution would imply the need to implement an entire stack-based VM on top of EVM. Instead, we should consider using the already available, far more flexible EVM directly for update validation. Similarly to Ethereum addresses, the feed address could correspond to either an external address (as it currently does) requiring verification or a contract address, in which case the chunk would be submitted to the contract at that address for validation up to a certain gas amount.

**Comment by jpeletier** [comment]
This is the response I was preparing, I'll leave it here for reference.

Hi @nagydani, thank you for your comments.

> Swarm feeds are a lightweight substitute for blockchain-based updates, a scalability aid.

We have found that Swarm feeds have actually grown past being just a blockchain scalability aid to be something that can actually live on its own.

> In a typical Swarm-based đapp, eventual consistency is achieved through regularly uploading the most recent state of a feed to the blockchain

We say "typical" here as if we had lots of examples already 😉. How people are going to build stuff on Swarm and Swarm feeds is yet to be seen. In Ethergit, for example, we are not uploading anything feeds-related to the blockchain. I am not saying everybody won't, but we are not.

> Thus, a self-validating mechanism should be conducive to being validated by smart contracts as well; the proposed solution would imply the need to implement an entire stack-based VM on top of EVM

For đapps that need to update state in the blockchain, they would not need to implement an entire stack-based VM on EVM. You don't need to execute scripts to validate them. For your  đapp, you would just need to *recognize* a script's bytecode, since in any case you won't want people to arbitrarily create any kind of script for your app. Thus, you would end up standardizing on a few types and have your smart contract easily recognize those.

In fact, even without bzz-script, you still have to somehow have a smart contract "parse" a feeds chunk header to know what to do with it. This parsing is not more difficult than recognizing a given standard bzz-script.

> Similarly to Ethereum addresses, the feed address could correspond to either an external address (as it currently does) requiring verification or a contract address, in which case the chunk would be submitted to the contract at that address for validation up to a certain gas amount.

If I understood correctly, you mean here that a given feed chunk could be of two types: either the author Ethereum address belongs to an individual with a corresponding private key (the way it works now), or the feed update "author" address is actually a smart contract address. Such smart contract would then export a function with a signature like this:
```solidity
function Validate(uint8[4096] memory chunk) public view  returns (bool)
```
Interestingly, this is a view function, so it would not require gas to execute.

This approach is interesting because you can just write a `Validate` function in solidity with whatever logic,
 and deploy it as part of a smart contract, essentially saying: *"This chunk is valid if Smart Contract `0xABCDE...` says it is!"*

However, my problems with this approach are:
* You depend on a geth connection to validate chunks. For each chunk that arrives, you have to call geth to execute this function and tell you whether to accept or drop the chunk. 
This is a lot of overhead for just one tiny chunk coming in.
* Each chunk does not carry all what is needed to validate it. If the contract state changes, it could mean that chunks that were previously valid now are not. Therefore, if you run the validate function against chunks 
already in your chunkstore, some could now be discarded.
* Although view functions do not consume gas, you will have to impose some sort of execution time limit in your geth node, otherwise someone could write a view function with a loop and have you burn cycles executing it.

bzz-script does not have the above three issues: proofs are contained in each chunk and challenges are immutable. Execution steps are very limited and it is not Turing-complete, so no loops.

**Comment by zelig** [comment]
❤️

**Pull request closed without merging**
