### PR TITLE
swarm/storage: fixed some code with hardcoded key length

### PR DESCRIPTION
**Pull request by jpeletier**
Found some hardcoded 32's in the `storage` package. Please check if I didn't go too far.

### CODE REVIEW

**Comment by jpeletier** [comment]
Yeah! PR #777 lucky number!!

**Comment by nolash** [comment]
@jpeletier I guess the rebase spun this PR out of scope?

**Comment by jpeletier** [comment]
@nolash ... yes. I just cherrypicked the commit on top of the new `develop`, so now this is mergeable.

**Review by zelig — CHANGES_REQUESTED** [review]
KeyLength should be `AddressSize`

**Comment by jpeletier** [comment]
I will change this when #784 is merged to avoid a conflict.
Note, though, that `KeyLength` constant was already there with this name, not created in this PR.

**Pull request closed without merging**
